---
- name: change_password_play
  hosts: all
  strategy: free
  gather_facts: false
  tasks: 
    - name: vars 호출
      include_vars: ../vars/passwd_vars.yml

    - name: 작업 실행자 조회
      delegate_to: "{{ localhost }}"
      run_once: true
      shell: |
        docker exec \
          -e PGPASSWORD={{ fap_db_password }} \
          -i pg-0 \
          psql \
          -U nds \
          -d fap \
          -t -A \
          -c "
          SELECT ui.user_name
          FROM job_info ji
          JOIN user_info ui
            ON ji.execute_by = ui.user_cd
          WHERE ji.job_id = {{ fap.job_id }};
          "
      register: execute_user
    
    - name: 작업 실행자 저장
      run_once: true
      set_fact:
        execute_user_name: "{{ execute_user.stdout | trim }}"
      
    - name: 날짜 연+월
      run_once: true
      set_fact:
        fap_today: "{{ lookup('ansible.builtin.pipe','date +%Y%m')}}" # 연 월 합친 변수 생성
      delegate_to: localhost

    - name: 현재 시간
      run_once: true
      set_fact:
        change_time: "{{ lookup('pipe', 'date +%H:%M:%S') }}"
      delegate_to: localhost
  
    - name: hosts 초기화
      raw: cat /dev/null > ~/.ssh/known_hosts
      delegate_to: localhost

    # - name: 계정 패스워드 출력
    #   debug:
    #     msg:
    #     - "sysmng: {{ ansible_password }}"
    #     - "root: {{ ansible_become_password }}"
    #   when: ansible_port != 5985
    
    # - name: 계정 패스워드 출력 Windows
    #   debug:
    #     msg:
    #     - "sysmng: {{ ansible_password }}"
    #   when: ansible_port == 5985

    - name: 이전 계정 정보 저장
      set_fact:
        before_user: "{{ ansible_user }}"
        before_pass: "{{ ansible_password }}"

    - name: 실행 계정 추출
      fap.common.get_credential:
        credential_name: "{{ fap_today }}"
        host_ip: "{{ fap.host_ip | default(omit) }}"
        host_name: "{{ fap.host_name | default(omit) }}"
        #credential_name: "pattern"
      register: user_info
      delegate_to: localhost

    - name: 실행 계정 패스워드 패턴 추출
      set_fact:
        month_user: "{{ user_info.data.username }}"
        month_pass: "{{ user_info.data.password }}"

    - name: 변경 계정 출력
      debug:
        msg:
          - "{{ month_user }}"
          - "{{ month_pass }}"

    - name: 접속 확인
      raw: uname -s
      register: uname_result
      ignore_errors: yes
      when: ansible_port != 5985

    - name: 접속 결과 출력
      fail:
        msg: "접속 불가합니다. 통신 확인"
      when: 
        - uname_result.rc != 0  # 명령이 정상적으로 실행되지 않은 경우에만 중단
        - ansible_port != 5985

    # - name: 변경 OS 출력
    #   debug:
    #     var: uname_result.stdout

    - name: python tasks
      include_tasks: ../tasks/python_passwd.yml
      when: ansible_port != 5985

    - name: PASS 변경 결과 보고서 생성 로직 호출
      include_tasks: ../tasks/password_report_tasks.yml

    # - name: DB Save
    #   include_tasks: ../tasks/py_passwd_dbsave.yml
    
    - name: python 패스워드 변경 실패
      fail:
        msg: "패스워드 변경 확인 필요로 인벤토리 업데이트 중지"
      when: >-
        '오류' in password_value.stdout or
        '프롬프트를 찾을 수 없습니다.' in password_value.stdout or
        '확인이 필요' in password_value.stdout or
        '실패' in password_value.stdout

    - name: "FAP root password 변경 "
      fap.common.change_host_credential:
        host_ip: "{{ fap.host_ip }}"
        become_password: "{{ month_pass }}"
      delegate_to: localhost
      when: month_user == 'root'

    - name: "FAP sysmng password 변경 "
      fap.common.change_host_credential:
        host_ip: "{{ fap.host_ip }}"
        password: "{{ month_pass }}"
      delegate_to: localhost
      register: result_credential
      when: month_user == 'sysmng'