---
- name: 일시 생성
  set_fact:
    today: "{{ lookup('ansible.builtin.pipe', 'date +%Y%m%d') }}"
  delegate_to: localhost

- name: hostname 수집
  win_shell: hostname
  register: hostname_check

# -- 작업 스케줄러 등록 및 실행 
# - name: wasadmin 작업스케줄러 등록
#   win_scheduled_task:
#     name: RunAsWasAdmin
#     description: Run a command as wasadmin
#     actions:
#       - path: powershell.exe
#         arguments: '-Command "jeusadmin -licenseinfo > C:\temp\licenseinfo.txt"'
#     username: wasadmin
#     password: P@ehfhtm#1    
#     logon_type: password # 사용자 계정으로 명확하게 실행
#     run_level: highest
#     state: present
#     enabled: yes
#     hidden: no
#     frequency: once
#     one_time: yes

# - name: 작업 상태 확인
#   win_shell: schtasks /query /tn "RunAsWasAdmin" /v /fo list
#   args:
#     executable: powershell
#   register: status

# - name: 작업스케줄러 실행 - 변경 작업 전
#   win_shell: schtasks /run /tn "RunAsWasAdmin"
#   args:
#     executable: powershell

- name: 결과 확인 - 변경 작업 전
  win_shell: Get-Content "C:\\temp\\licenseinfo.txt"
  register: license_before

# - name: licenseinfo 출력 - 변경 작업 전
#   debug:
#     msg: "{{ license_before.stdout }}"

## -- 변경 작업 시작 
# - name: 기존 라이센스 백업
#   win_shell: |
#     cd {{ output_path_win }}
#     Rename-Item -Path "{{ output_path_win }}\license" -NewName "license_{{ today }}"
#   args: 
#     executable: powershell

# - name: 임시 디렉토리 생성 (C:\temp)
#   win_file:
#     path: "{{ temp_path_win }}"
#     state: directory

# - name: JEUS_DEMO 복사
#   win_copy:
#     src: "{{ jeus_zip_path }}"
#     dest: "{{ temp_path_win }}\\JEUS_DEMO.zip"

# - name: JEUS_DEMO 압축 해제 (모듈 방식)
#   win_unzip:
#     src: "{{ temp_path_win }}\\JEUS_DEMO.zip"
#     dest: "{{ temp_path_win }}\\JEUS_DEMO"
#     delete_archive: yes  # 압축 파일 삭제 여부

# - name: JEUS 라이선스 복사 (license_호스트명)
#   win_copy:
#     src: "{{ temp_path_win }}\\JEUS_DEMO\\license_{{ hostname_check.stdout | trim }}"
#     dest: "{{ output_path_win }}"
#     remote_src: yes

# - name: 라이선스 파일 이름 변경 (license_호스트명 → license)
#   win_shell: |
#     Rename-Item -Path "{{ output_path_win }}\license_{{ hostname_check.stdout | trim }}" -NewName "license"
#   args:
#     executable: powershell

# - name: JEUS_DEMO 디렉토리 삭제
#   win_file:
#     path: "{{ temp_path_win }}\\JEUS_DEMO"
#     state: absent

# - name: 작업스케줄러 실행 - 변경 작업 후
#   win_shell: schtasks /run /tn "RunAsWasAdmin"
#   args:
#     executable: powershell

- name: 결과 확인 - 변경 작업 후
  win_shell: Get-Content "C:\\temp\\licenseinfo2.txt"
  register: license_after

# - name: licenseinfo 출력 - 변경 작업 후
#   debug:
#     msg: "{{ license_after.stdout }}"

- name: web_check 생성 (before + after)
  set_fact:
    web_check: |
      {{ license_before.stdout }}
      {{ license_after.stdout }}

- name: make json
  command: /usr/bin/python3 ../vars/make_json.py
  environment:
    jeus_id: "wasadmin"
    host_ip: "{{ fap.host_ip }}"
    device_name: "{{ fap.host_name }}"
    port: "{{ ansible_port }}"
    web_check: "{{ web_check }}"
    json_path: "{{ json_path }}"
    output_path: "{{ save_path }}"
    file_name: "{{ ex_file_name }}"
  register: report_result
  delegate_to: localhost